### ISSUE TITLE
future-webpack5-moved-to-webpack5

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/subject-id-gen#7]
https://github.com/AMP-SCZ/subject-id-gen/blob/a3b8a8191dd90e6b7bffe1ff68b6d9baf2a67326/next.config.js.sample#L3-L5

```bash
[user@~ subject-id-gen]$ node_modules/yarn/bin/yarn build
yarn run v1.22.11
$ next build
info  - Loaded env from /home/tb571/subject-id-gen/.env.local

> Build error occurred
Error: `future.webpack5` in `next.config.js` has moved to the top level `webpack5` flag https://nextjs.org/docs/messages/future-webpack5-moved-to-webpack5
    at Object.loadWebpackHook (/home/tb571/subject-id-gen/node_modules/next/dist/server/config-utils.js:93:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loadConfig [as default] (/home/tb571/subject-id-gen/node_modules/next/dist/server/config.js:332:5)
    at async Span.traceAsyncFn (/home/tb571/subject-id-gen/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /home/tb571/subject-id-gen/node_modules/next/dist/build/index.js:83:24
    at async Span.traceAsyncFn (/home/tb571/subject-id-gen/node_modules/next/dist/telemetry/trace/trace.js:60:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

https://nextjs.org/docs/messages/future-webpack5-moved-to-webpack5

**Comment by tashrifbillah** [comment]
The issue happens when next is upgraded to `version "11.1.0"`

https://github.com/AMP-SCZ/subject-id-gen/security/dependabot/yarn.lock/next/open

Issue #6
